FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openssh-server python3 python3-pip && \
    mkdir /var/run/sshd

RUN useradd -rm -d /home/user -s /bin/bash -g root -G sudo -u 1001 user && \
    echo 'user:user_password' | chpasswd && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    echo 'AllowUsers user' >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
